### ISSUE TITLE
Crash on registration

### ISSUE THREAD

**Issue by Pungsnigel** [oney/react-native-gcm-android#33]
I'm getting the following exception when trying to add an event lister for 'register' events. Any ideas?

```
FATAL EXCEPTION: IntentService[GcmRegistrationService] at com.oney.gcm.GcmRegistrationService.onHandleIntent(GcmRegistrationService.java:30)
Process: com.myapp, PID: 23592
android.content.res.Resources$NotFoundException: String resource ID #0x0
 at android.content.res.Resources.getText(Resources.java:321)
 at android.content.res.Resources.getString(Resources.java:407)
 at android.content.Context.getString(Context.java:377)
 at com.oney.gcm.GcmRegistrationService.onHandleIntent(GcmRegistrationService.java:31)
 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:135)
 at android.os.HandlerThread.run(HandlerThread.java:61)
Force finishing activity 1 com.myapp/.MainActivity
Tried to remove non-existent frame callback
```

**Comment by oney** [comment]
Do you have `android/app/google-services.json` file?

**Comment by Pungsnigel** [comment]
Yes. I'm not sure how to validate that it's correct, but it is there.

**Comment by oney** [comment]
Please try this [solution](http://stackoverflow.com/a/30723037/1518075).
Or, remove `android/build` and `android/app/build` directories and re-run.
The last solution is finding `project_number` in `android/app/google-services.json`(eg `309660514018` in TestGcm project), and hard code the `projectNumber` in `node_modules/react-native-gcm-android/android/src/main/java/com/oney/gcm/GcmRegistrationService.java`
```java
// int resourceId = resources.getIdentifier("gcm_defaultSenderId", "string", packageName);
// String projectNumber = getString(resourceId);
String projectNumber = "309660514018";
```

**Comment by Pungsnigel** [comment]
@oney First suggested solution worked well, thanks! Closing.
