### ISSUE TITLE
error Unforturnately, appName has stopped.

### ISSUE THREAD

**Issue by 2ducanhpham** [oney/react-native-gcm-android#43]
Hi!
error push notifycation when app killed in Android

My change log:

02-18 11:13:49.965 21283-21283/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: vn.evanews.evanews, PID: 21283
                                                   java.lang.RuntimeException: Unable to start service com.oney.gcm.BackgroundService@42371058 with Intent { cmp=vn.evanews.evanews/com.oney.gcm.BackgroundService (has extras) }: java.lang.NullPointerException
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3127)
                                                       at android.app.ActivityThread.access$2200(ActivityThread.java:174)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:146)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5756)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.NullPointerException
                                                       at com.oney.gcm.BackgroundService.getBuildConfigDEBUG(BackgroundService.java:64)
                                                       at com.oney.gcm.BackgroundService.onStartCommand(BackgroundService.java:28)
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3110)
                                                       at android.app.ActivityThread.access$2200(ActivityThread.java:174) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:146) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5756) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
02-18 11:13:49.975 749-21308/? E/android.os.Debug: !@sDumpstate is still running

Please help me!

**Comment by jlugner** [comment]
@2ducanhpham Did you solve this?

**Comment by jeffjose** [comment]
Seeing the same error. Using a similar setup as the demo-app. Works great in background mode, but crashes after I kill the app.

Jeff
